### ISSUE TITLE
Add dois of software used to paper.md

### ISSUE THREAD

**Issue by platipodium** [hainegroup/oceanspy#107]
Please complete your reference list in `paper.md`/`paper.bib` with dois for all software referenced (dask/xarray/xgcm/...) to continue your review evaluation https://github.com/openjournals/joss-reviews/issues/1506

**Comment by malmans2** [comment]
@platipodium all entries other than dask have a doi now. I couldn't find a doi for dask (I also checked Zenodo), and we are using the [official citation](http://docs.dask.org/en/latest/cite.html).

**Comment by platipodium** [comment]
Thanks for fixing this immediately.  I don't like the dask official, as it is not a persistent identifier, but I guess we'll have to live with that.
