### ISSUE TITLE
Time range for dataset  of EGshelfIIseas2km_ERAI

### ISSUE THREAD

**Issue by hedongzi2000** [hainegroup/oceanspy#112]
* OceanSpy version:

### Description

when I uses the following code as a try to exact data like in the tutorials.

od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ERAI_6H')

# CS information
lats_Kogur = [ 64.81]
lons_Kogur = [-36.15]
depth_Kogur = [0, -700]

# Select time range:
# September 2007, extracting one snapshot every day
timeRange = ['2007-09-01', '2008-08-31T18']
timeFreq = '1D'

# Extract mooring array and fields used by this notebook
od_moor2 = od.subsample.mooring_array(Xmoor=lons_Kogur,
                                     Ymoor=lats_Kogur,
                                     ZRange=depth_Kogur,
                                     timeFreq=timeFreq,
                                     varList=['Temp', 'S',
                                              'U', 'V'])

error information is like:

Cutting out the oceandataset.

TypeErrorTraceback (most recent call last)
<ipython-input-63-5afd03eef8df> in <module>
     15                                      timeFreq=timeFreq,
     16                                      varList=['Temp', 'S',
---> 17                                               'U', 'V'])

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in mooring_array(self, **kwargs)
   1237     @_functools.wraps(mooring_array)
   1238     def mooring_array(self, **kwargs):
-> 1239         return mooring_array(self._od, **kwargs)
   1240 
   1241     @_functools.wraps(survey_stations)

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in mooring_array(od, Ymoor, Xmoor, **kwargs)
    590     if "add_Hbdr" not in kwargs:
    591         kwargs['add_Hbdr'] = True
--> 592     od = od.subsample.cutout(**kwargs)
    593 
    594     # Message

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in cutout(self, **kwargs)
   1233     @_functools.wraps(cutout)
   1234     def cutout(self, **kwargs):
-> 1235         return cutout(self._od, **kwargs)
   1236 
   1237     @_functools.wraps(mooring_array)

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in cutout(od, varList, YRange, XRange, add_Hbdr, mask_outside, ZRange, add_Vbdr, timeRange, timeFreq, sampMethod, dropAxes)
    446         # Infer original frequency
    447         inFreq = _pd.infer_freq(ds.time.values)
--> 448         if timeFreq[0].isdigit() and not inFreq[0].isdigit():
    449             inFreq = '1'+inFreq
    450 

TypeError: 'NoneType' object is not subscriptable

Could you help me to fix the problem? thanks.

Best,
Yunchang

**Comment by malmans2** [comment]
Hi Yunchang,
The problem is that the ERAI dataset is not sorted in time, so pandas is not able to infer the original time frequency. I'm just going to sort the dataset itself, so reading the data is quick and we don't have to make any change to the code.
Thanks!

**Comment by malmans2** [comment]
@hedongzi2000 give it a try. It should be fixed now.

**Comment by hedongzi2000** [comment]
Works well now, thanks a lot :)
