### ISSUE TITLE
Continuous Integration failure

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#118]
Travis CI is reporting a failure. The log file [here](https://travis-ci.org/malmans2/oceanspy) only shows errors in functions that use intake. I think the problem is that intake doesn't get installed properly, so hopefully we only have to fix the environment setup of Travis.

**Comment by malmans2** [comment]
I think `intake-xarray` changed a little and additional arguments such as `engine` and `drop_variables` must be passed in a dictionary named `xarray_kwargs`. Here is an example from the SciServer catalog:
https://github.com/malmans2/oceanspy/blob/6082264300e30a8b81c559f4c977aa17c732b1c6/sciserver_catalogs/catalog_xarray.yaml#L13-L14

The current catalog works fine on SciServer though because we didn't update the Oceanography image.

**Comment by malmans2** [comment]
Should be fixed! I just updated the catalogs.

**Comment by asiddi24** [comment]
The tests are working fine now ! Travis CI doesn't show any errors now. Thanks for fixing the bug @malmans2 !
