### ISSUE TITLE
Volumetric census using xhistogram

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#119]
[xhistogram](https://xhistogram.readthedocs.io) seems more stable so we can probably use it to update the volumetric census in the tutorial notebook by @ThomasHaine

**Comment by ThomasHaine** [comment]
Good idea!


On Aug 23, 2019, at 2:02 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


xhistogram<https://xhistogram.readthedocs.io/> seems more stable so we can probably use it to update the volumetric census in the tutorial notebook by @ThomasHaine<https://github.com/ThomasHaine>

**Comment by ThomasHaine** [comment]
Does xhistogram play well with dask?

**Comment by ThomasHaine** [comment]
OK, I run the code below on SciServer Oceanography, based on the xhistogram tutorial. The first plot (without cell volume weights) works OK. The second one (with cell volume weights) doesn't. Why?

`# Setup environment:
import oceanspy as ospy

# Additional packages
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
from xhistogram.xarray import histogram

# Open the oceandataset and compute the potential density anomaly:
od_snapshot = ospy.open_oceandataset.from_catalog('get_started')

# histogram of number of data points. From xhistogram tutorial:
sbins = np.arange(25.5,35.5, 0.0125)
tbins = np.arange(-2, 10, 0.05)
hTS = histogram(od_snapshot.dataset['S'].mean('time'), od_snapshot.dataset['Temp'].mean('time'), bins=[sbins, tbins])
plt.subplot(2,1,1)
np.log10(hTS.T).plot(levels=31)

# Now re-compute using volume weights
dVol = od_snapshot.dataset.drC * od_snapshot.dataset.dxC * od_snapshot.dataset.dyC
hTSw = histogram(od_snapshot.dataset['S'].mean('time'), od_snapshot.dataset['Temp'].mean('time'), bins=[sbins, tbins], weights=dVol)
plt.subplot(2,1,2)
np.log10(hTSw.T).plot(levels=31)`

**Comment by malmans2** [comment]
Memory Error: You are using the wrong dX, dY, dZ and you are creating a huge dVol.
Check its shape: (Zp1: 56, Y: 154, Xp1: 208, Yp1: 155, X: 207)

You could use OceanSpy to create the volume weights. It also takes care of HFac.
```python
dVol = ospy.compute.weighted_mean(od_snapshot, varNameList='S', axesList=['X', 'Y', 'Z'])['weight_S']
```

**Comment by malmans2** [comment]
BTW, something doesn't look right:

The colorbar range changes a lot with or without weights.
Also, by default the `dVol` created using OceanSpy has a `time` dimension. But the weights are the same at each timestep (I double checked!). However, the results using `weights=dVol` and `weights=dVol.isel(time=0)` are slightly diffent.

**Comment by ThomasHaine** [comment]
Thanks!  It works now. Let's talk next week about what else is needed to finish this off. 
I think the colorbar changes because the weighted histogram uses the volumes in `dVol`. I'm surprised there's a difference between `weights=dVol` and `weights=dVol.isel(time=0)`.

**Comment by malmans2** [comment]
Sounds good!
I just realized you were averaging S and T in time.
The `isel` problem goes away if I use:
```python
dVol = ospy.compute.weighted_mean(od_snapshot,
                                  varNameList='S',
                                  axesList=['X', 'Y', 'Z'])['weight_S']
hTSw = histogram(od_snapshot.dataset['S'],
                 od_snapshot.dataset['Temp'], bins=[sbins, tbins], weights=dVol)
```
I think that, insead of raising an error, something weird is happening internally when T and S don't have time while `weights` does.

**Comment by ThomasHaine** [comment]
Understood. Without the time averaging, the histogram is (slightly) different. I guess:

`hTSw = histogram(od_snapshot.dataset['S'].mean('time'), od_snapshot.dataset['Temp'].mean('time'), bins=[sbins, tbins], weights=dVol)`

should throw an error because of the dimension mismatch.
