### ISSUE TITLE
Issue with "EGshelfSJsec500m_6H_hydro" dataset

### ISSUE THREAD

**Issue by hooteoos-waltz** [hainegroup/oceanspy#123]
* OceanSpy version:
(default installation on Oceanography image at Sciserver)
### Description

I am trying to sub-sample mooring array in EGshelfSJsec500m_6H_hydro modeloutput, and I get following error. Note that with exact same code if I use "EGshelfIIseas2km_ASR_full" or "EGshelfIIseas2km_ERAI_6H" outputs I do not get errors.

### What I Did

```
# Import oceanspy
import oceanspy as ospy

# Import additional packages used in this notebook
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# Start client
from dask.distributed import Client
client = Client()
client

od=ospy.open_oceandataset.from_catalog('EGshelfSJsec500m_6H_hydro')
# Latrabjarg information
lats_LL =[65.4857, 66.7972] 
lons_LL = [-24.5991, -29.7641]
depth_LL = [0, -700]

# Select time range:
# extracting one snapshot every 1 day
timeRange = ['2003-06-01', '2003-08-30']
timeFreq = '1D'

# Extract mooring array and fields used by this notebook
od_moor = od.subsample.mooring_array(Xmoor=lons_LL,
                                     Ymoor=lats_LL,
                                     ZRange=depth_LL,
                                     timeRange=timeRange,
                                     timeFreq=timeFreq,
                                     varList=['Temp', 'S'
                                              ])

ValueErrorTraceback (most recent call last)
<ipython-input-31-0639d614b3ac> in <module>
     15                                      timeRange=timeRange,
     16                                      timeFreq=timeFreq,
---> 17                                      varList=['Temp', 'S'
     18                                               ])

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in mooring_array(self, **kwargs)
   1237     @_functools.wraps(mooring_array)
   1238     def mooring_array(self, **kwargs):
-> 1239         return mooring_array(self._od, **kwargs)
   1240 
   1241     @_functools.wraps(survey_stations)

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in mooring_array(od, Ymoor, Xmoor, **kwargs)
    590     if "add_Hbdr" not in kwargs:
    591         kwargs['add_Hbdr'] = True
--> 592     od = od.subsample.cutout(**kwargs)
    593 
    594     # Message

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in cutout(self, **kwargs)
   1233     @_functools.wraps(cutout)
   1234     def cutout(self, **kwargs):
-> 1235         return cutout(self._od, **kwargs)
   1236 
   1237     @_functools.wraps(mooring_array)

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/subsample.py in cutout(od, varList, YRange, XRange, add_Hbdr, mask_outside, ZRange, add_Vbdr, timeRange, timeFreq, sampMethod, dropAxes)
    543 
    544         # Compute missing variables
--> 545         od = _compute._add_missing_variables(od, varList)
    546 
    547         # Drop useless

~/miniconda3/envs/Oceanography/lib/python3.7/site-packages/oceanspy/compute.py in _add_missing_variables(od, varList, FUNC2VARS)
    129                          ' please open an issue on GitHub:'
    130                          '\n https://github.com/malmans2/oceanspy/issues'
--> 131                          ''.format(var_error))
    132 
    133     # Compute new variables

ValueError: These variables are not available and can not be computed: ['Temp'].
If you think that OceanSpy should be able to compute them, please open an issue on GitHub:
 https://github.com/malmans2/oceanspy/issues
```
The variables Temp and S exists in the data-set but I get the above error that these variables are not available! What is the problem?

**Comment by malmans2** [comment]
There is a bug here:
https://github.com/malmans2/oceanspy/blob/9c97a0d968eadf64dba574b6a99d9a43523e2f72/oceanspy/compute.py#L112-L117
The function that add missing variables should check first if there are aliases. Temperature of MITgcm output stored in binary is named T instead of Temp.

**Comment by malmans2** [comment]
Never mind, disregard my previous comment: https://github.com/malmans2/oceanspy/issues/123#issuecomment-537639117.
There is no bug, but there was an error in the SciServer catalog.
It's fixed, all you have to do is to re-run your code.

**Comment by malmans2** [comment]
mmmm, I do have to make a change in order to have consistent variable names.
For the old setup you are supposed to use the variable name 'T' rather than 'Temp'.

**Comment by malmans2** [comment]
#124 fixes this issue. I'll merge as soon as someone reviews it.
When it's merged, you'll have to install the master branch of OceanSpy on SciServer.
The correct syntax will be:
```python
od_moor = od.subsample.mooring_array(Xmoor=lons_LL,
                                     Ymoor=lats_LL,
                                     ZRange=depth_LL,
                                     timeRange=timeRange,
                                     timeFreq=timeFreq,
                                     varList=['T', 'S' ])
```
The reason is that `T` is the original name of temperature in `EGshelfSJsec500m_6H_hydro`.

**Comment by hooteoos-waltz** [comment]
It worked just by rerunning it (and use Temp variable).

**Comment by malmans2** [comment]
It works now, but it's conceptually wrong and in the future your scripts will break.
If you want to avoid that, download [my_catalog_xmitgcm.txt](https://github.com/malmans2/oceanspy/files/3684049/my_catalog_xmitgcm.txt), and use it to open the datasets that need `xmitgcm`:
```python
od = ospy.open_oceandataset.from_catalog('EGshelfSJsec500m_6H_hydro', 'my_catalog_xmitgcm.txt')
```
It will rename the variable `T` to `Temp` rather than creating an alias, so `varList=['Temp', 'S']` is correct. 

PS: I named it with `.txt` extension just because otherwise I can't upload it here. But it's better if you re-name it using `.yaml`!

**Comment by hooteoos-waltz** [comment]
Great! so should I put  my_catalog_xmitgcm.yaml in my code directory?
Also, should I update the installation or or the Oceanography notebook is always up to date?

**Comment by malmans2** [comment]
You can put it wherever you like. The second argument of `from_catalog` is the `path\of\catalog.yaml`. 
The Oceanography image doesn't update automatically, so you'll have to do it by yourself. But we didn't push the fix yet. If you use the customized catalog you avoid the bug, so your scripts won't break when we'll push #124.

**Comment by hooteoos-waltz** [comment]
OK, it's working with the my_catalog_xmitgcm.yaml. So feel free to close the issue if you'd like.
