### ISSUE TITLE
Migration Box to OneDrive

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#127]
See email below. All our test datasets are currently hosted by Box. Let's keep an eye on the migration and, when it's done, switch the shared links from Box to OneDrive:

> IT at Johns Hopkins is ending their agreement with Box and will be using Microsoft OneDrive as their new online storage provider. As part of this change, all data currently in your Box account will be migrated to OneDrive. Data will be migrated to OneDrive in two phases. The first phase will copy all existing data from Box to OneDrive, and Box will continue to function normally. The second phase will be a “copy changed files” and write access to Box WILL STOP when this copy is complete. This means that no new data can be added to Box after the second copy finishes, and files must be shared out to others using OneDrive. All Box accounts will be terminated in April of 2020.
> 
>  
> Important things to note:
> 
> ***Any files in Box which are shared will have to be shared out again once copied over to OneDrive.  (Since external collaborations will not be recreated, a report will be provided for users to review all external collaborations which can be recreated once the migration/copy is completed)
> 
> ***Any file/folder structure exceeding 350 characters will not be migrated/copied to JHOneDrive.
> 
>  
> 
> Members of the Krieger School of Arts and Sciences will begin the migration on November 14th.

**Comment by ThomasHaine** [comment]
Is the migration now complete?  My JHBox was moved to One Drive a few days ago.

**Comment by malmans2** [comment]
Yes! I'll cange all the paths next week. Maybe we could also update the Oceanography image with the latest packages. Here is what I have to remember to change:
- [ ] Links used in the tutorials
- [ ] Links used by pytest
- [ ] Links used in binders

**Comment by malmans2** [comment]
To get a download from OneDrive: get a shared link, remove everything after `?` and add `download=1`.
