### ISSUE TITLE
Improve transport through vertical sections

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#13]
* OceanSpy version: 0.0.9

### Description
Add a function to compute transports through vertical sections

**Comment by malmans2** [comment]
@renskegelderloos: I've added "mooring_array" and transport functions. 
You can start using it, but I need to make a few updates: add tutorial, add interactive functions, check syntax and the way the 2 paths are outputted, ...

**Comment by malmans2** [comment]
Also, decide what to do with path 1/2, their bathymetry, and zeros due to corners.

**Comment by renskegelderloos** [comment]
Document the meaning of the xpath and ypath dimensions

**Comment by renskegelderloos** [comment]
There is a bug in the current transport calculation. If the moorings are close together and not on a meridional or zonal section, the algorithm that finds the 'zigzag' path occasionally skips grid points.
