### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Nikon-V** [hainegroup/oceanspy#133]
* OceanSpy version: latest

### Description

I was just trying to load ocean spy on conda (spyder 3.7) on my mac and it loads an environnement in the console but after two days of continuous loading i gave up it takes too much time and i don't know why !? Can someone help ? i'm not a pro in coding so maybe this explain that... here is what i see in the console : 
<img width="779" alt="Capture d’écran 2019-12-24 à 23 49 03" src="https://user-images.githubusercontent.com/59309790/71543374-054a7e00-2972-11ea-9297-d96e193c423f.png">

**Comment by malmans2** [comment]
Hi @Nikon-V,
I've never used Spyder myself. Hopefully @asiddi24 can be more helpful.

In the meantime, have you tried to install OceanSpy and its dependencies in a separate environment?
From terminal:
1. `conda create --name OceanSpy`
2. `conda activate OceanSpy`
3. `conda install -c conda-forge oceanspy dask distributed bottleneck netCDF4 xarray cartopy esmpy intake-xarray geopy xesmf esmf xgcm Ipython tqdm pytest ffmpeg xmitgcm`

Now you should be able to work in the OceanSpy environment. If you use Spyder, make sure you select the OceanSpy environment. My guess is that it's easy to switch between conda environments in Spyder, but if this is not the case I think @asiddi24 knows how to do it.

**Comment by Nikon-V** [comment]
Thank you for the quick answer :) i've executed the code lines in terminal but now as you mentionned when i import oceanspy it says “no module named oceanspy“ meaning i'm in the wrong environnement but i don't know how to change it hopefuly asiddi24 can help me. Thank very much.

**Comment by Nikon-V** [comment]
All right so i managed to select the environnement in spyder with the modular method using this : https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
So now it works propely !
Big thank you @malmans2 for your help ! See you soon

**Comment by asiddi24** [comment]
@Nikon-V , could you enumerate what you did for your original problem ? 

Did you use conda while running spyder to install oceanspy as  ` conda install -c conda-forge oceanspy ` ?

and then ran `import oceanspy`  in the spyder console ?

**Comment by Nikon-V** [comment]
@asiddi24 i used conda while running spyder and i've done what's written in the installation section of oceanspy website : $ conda update conda
$ conda config --set channel_priority strict
$ conda config --prepend channels conda-forge
$ conda install -y oceanspy dask distributed bottleneck netCDF4 "xarray>=0.11.3" cartopy esmpy ffmpeg intake-xarray geopy "xgcm>=0.2" xesmf Ipython tqdm "xmitgcm>=0.3"
$ pip install ffmpeg
So it's starts slowly but it start and it says all the time " finding the shortest path for..." while the purcentage of achievement still grow, so i waited two days and a half (yeah i don't give up) and then it started downloading an other thing an so i stopped it..

By the way i'm trying to use oceanspy for the particles model (but not on sciserver) and i have trouble making it works : when i ran all the commands ( i want trajectories ) it runs infinite, and when i stop it : gotit = waiter.acquire(True, timeout) l 306 so i'm looking for it currently but if anyone knows help would be appreciated. :))

**Comment by Nikon-V** [comment]
i would like to get particles mouvement in west atlantic ocean but on my machine do you know where i can find datas for it ?

**Comment by asiddi24** [comment]
@Nikon-V it seems to be working on my local machine and I tried repeating it on Sciserver as well. The reason that 


> In the meantime, have you tried to install OceanSpy and its dependencies in a separate environment?
> From terminal:
> 
>     1. `conda create --name OceanSpy`
> 
>     2. `conda activate OceanSpy`
> 
>     3. `conda install -c conda-forge oceanspy dask distributed bottleneck netCDF4 xarray cartopy esmpy intake-xarray geopy xesmf esmf xgcm Ipython tqdm pytest ffmpeg xmitgcm`
> 
> 
this works is because you are creating a new environment to work in which does not conflict with any previous versions of packages already installed in your base environment. I tried installing python 3.7 in my base environment and then ran the whole installation and I get the kind of error that you get too. 

So, just make sure that you always make a new environment when working with multiple dependencies and install them in the working environment. In essence, before doing this

> @asiddi24 i used conda while running spyder and i've done what's written in the installation section of oceanspy website : $ conda update conda
> $ conda config --set channel_priority strict
> $ conda config --prepend channels conda-forge
> $ conda install -y oceanspy dask distributed bottleneck netCDF4 "xarray>=0.11.3" cartopy esmpy ffmpeg intake-xarray geopy "xgcm>=0.2" xesmf Ipython tqdm "xmitgcm>=0.3"
> $ pip install ffmpeg

create a new environment, activate it and then run the installation.

That should solve your issue, hopefully.

**Comment by ThomasHaine** [comment]
@asiddi24, close issue?

**Comment by ThomasHaine** [comment]
Stale issue. Closing now. Reopen if this is still live!
