### ISSUE TITLE
Codecov is not set up right

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#147]
I'm very confused, does anyone understand what's going on with codecov?
Since @Mikejmnez last commit yesterday, it shows the coverage of the PR, and I think the default codecov branch points to  @Mikejmnez master: https://codecov.io/gh/hainegroup/oceanspy/branches

I'm sure yesterday the correct coverage was displayed, so something must have happened yesterday...
I'm not completely sure, but I think I deleted old branches yesterday... Maybe that's why it's only showing up today? Or maybe @Mikejmnez changed something?

**Comment by malmans2** [comment]
Mmmm, I think the problem is that PR #146 is named master (@Mikejmnez are you pushing from master?), which conflicts with the name of oceanspy master branch. I've never done a PR without creating a new separate branch though (i.e., I never push from the master branch of the fork), so I might be wrong...

If this is the problem, the only workaround I can see is to close #146 in favor of a new PR (identical) but with a different branch name... Does it make sense?

**Comment by Mikejmnez** [comment]
> Mmmm, I think the problem is that PR #146 is named master (@Mikejmnez are you pushing from master?), which conflicts with the name of oceanspy master branch. I've never done a PR without creating a new separate branch though (i.e., I never push from the master branch of the fork), so I might be wrong...
> 
> If this is the problem, the only workaround I can see is to close #146 in favor of a new PR (identical) but with a different branch name... Does it make sense?

Oh! I made a commit to the PR by updating the intake catalog entries with the correct url paths (I think you and I were having some issues with that)... I have made changes to the code before just like I did yesterday since I initiated this PR, so nothing new on my end, but I don't really fully understand this. 

I am pushing from master, but I have done so in other times (prob a bad practice, but I doubt something like this would create such an error as to confuse the upstream origin...) Also, my default branch on the ```oceanspy``` fork isn't the master branch (in codecov it states ```default``` ).

**Comment by malmans2** [comment]
I'm not sure why the problem did not show up before, but if you look [here](https://codecov.io/gh/hainegroup/oceanspy/branches) master (and therefore default) points to your repository. As the branch names in codecov don't have prefixes (e.g., hainegroup:master, Mikejmnez:master), I think this is creating conflicts.
Could you please try to submit a new PR, but using a branch name different than master? If everything looks good, we'll then close #146 and I think everything should work fine. We had some discussion in #146, so we'll just tag it the new PR for reference.
To create branches: `git checkout -b NAMEOFTHEBRANCH`
To push: `git push -u origin NAMEOFTHEBRANCH`

**Comment by asiddi24** [comment]
It looks like @Mikejmnez pushed commits to the master branch of the hainegroup/oceanspy and somehow not @Mikejmnez 's oceanspy.

**Comment by Mikejmnez** [comment]
> I'm not sure why the problem did not show up before, but if you look [here](https://codecov.io/gh/hainegroup/oceanspy/branches) master (and therefore default) points to your repository. As the branch names in codecov don't have prefixes (e.g., hainegroup:master, Mikejmnez:master), I think this is creating conflicts.
> Could you please try to submit a new PR, but using a branch name different than master? If everything looks good, we'll then close #146 and I think everything should work fine. We had some discussion in #146, so we'll just tag it the new PR for reference.
> To create branches: `git checkout -b NAMEOFTHEBRANCH`
> To push: `git push -u origin NAMEOFTHEBRANCH`

Sure I'll do that, seems like an easy fix!

**Comment by malmans2** [comment]
I made a minor change to the master, just to trigger travis, but master still points to @Mikejmnez master.
It might be that it was not updated just because travis failed, or that we should delete and recreate the codecov page.

**Comment by malmans2** [comment]
I think we just have to `Erase content`, but there's an issue.
I've opened a ticket here:
https://community.codecov.io/t/erase-content-not-working/1738

**Comment by malmans2** [comment]
Everything back to normal!
