### ISSUE TITLE
Pinned packages to fix test failures

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#152]
Tests are failing.
From a quick glance errors are due to incompatibility between xarray and pandas 1.1.0.

We can close this issue when we unpin the following packages:

- [x] pandas<1.1.0
- [x] black<20.8b1

**Comment by malmans2** [comment]
See https://github.com/pydata/xarray/issues/4319

**Comment by asiddi24** [comment]
So, waiting for the next xarray release then ? Or as pointed out, we keep pandas < 1.1.0

**Comment by malmans2** [comment]
Let's use pandas<1.1.0 for now. I'd say to keep this issue open until we can remove pandas from the environment list, so we don't forget to unpin pandas.

**Comment by malmans2** [comment]
I pinned black as well due to incompatibility with black-nb (see #156)
