### ISSUE TITLE
Trouble analyzing `DataSet` from `xmitgcm`

### ISSUE THREAD

**Issue by daanreijnders** [hainegroup/oceanspy#154]
* OceanSpy version: 0.1.0

### Description

I'm trying to analyze some mitgcm output, which I already have loaded into an `xarray.DataSet` using `xmitgcm`. I open the dataset into OceanSpy and set the correct coordinates. However, when I then try to plot a simple variable like the "Depth" (easiest example in your tutorial), I get an error. I am having a hard time figuring out what goes wrong. I'm also having issues with computations, for example of the divergence (see example below). Here I get a message that `['HFacC', 'HFacW']` are not available, but these are certainly present in `ds`; `xmitgcm` loads these correctly. 

I'm also wondering whether it would be possible to automatically set the grid from `xgcm`. `xgcm` seems to do a good job at inferring the grid with `xgcm.Grid(ds)`, so letting `xgcm` set the grid used in OceanSpy seems much more convenient than manually specifying it with `od.set_grid_coords()`.

P.S. Thanks for developing this package!

### What I Did

```Python
import xmitgcm
import oceanspy as ospy

ds = xmitgcm.open_mdsdataset("PATH", prefix=["surfDiag", "dynDiag"], calendar="360_days",
                             read_grid=True, geometry="cartesian")
od = ospy.OceanDataset(ds)
od = od.set_grid_coords(
    {
        "time": {"time": 0},
        "X": {"XC": 0, "XG": -0.5},
        "Y": {"YC": 0, "YG": -0.5},
        "Z": {"Z": 0, "Zl": -0.5},
    },
    overwrite=True
)
```
Plotting
```Python
ax = od.plot.horizontal_section(varName="Depth")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-87-769b050fb773> in <module>()
----> 1 ax = od.plot.horizontal_section(varName="Depth")

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/oceanspy/plot.py in horizontal_section(self, **kwargs)
   1063     @_functools.wraps(horizontal_section)
   1064     def horizontal_section(self, **kwargs):
-> 1065         return horizontal_section(self._od, **kwargs)
   1066 
   1067     @_functools.wraps(vertical_section)

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/oceanspy/plot.py in horizontal_section(od, varName, plotType, use_coords, contourName, meanAxes, intAxes, contour_kwargs, clabel_kwargs, cutout_kwargs, **kwargs)
    680     args = {'x': X_name, 'y': Y_name, **kwargs}
    681     plotfunc = eval('_xr.plot.'+plotType)
--> 682     p = plotfunc(da, **args)
    683 
    684     # Contour

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/xarray/plot/plot.py in newplotfunc(darray, x, y, figsize, size, aspect, ax, row, col, col_wrap, xincrease, yincrease, add_colorbar, add_labels, vmin, vmax, cmap, center, robust, extend, levels, infer_intervals, colors, subplot_kws, cbar_ax, cbar_kwargs, xscale, yscale, xticks, yticks, xlim, ylim, norm, **kwargs)
    650 
    651         xlab, ylab = _infer_xy_labels(
--> 652             darray=darray, x=x, y=y, imshow=imshow_rgb, rgb=rgb
    653         )
    654 

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/xarray/plot/utils.py in _infer_xy_labels(darray, x, y, imshow, rgb)
    378         y = darray.dims[0] if x == darray.dims[1] else darray.dims[1]
    379     else:
--> 380         _assert_valid_xy(darray, x, "x")
    381         _assert_valid_xy(darray, y, "y")
    382 

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/xarray/plot/utils.py in _assert_valid_xy(darray, xy, name)
    404     if xy not in valid_xy:
    405         valid_xy_str = "', '".join(sorted(valid_xy))
--> 406         raise ValueError(f"{name} must be one of None, '{valid_xy_str}'")
    407 
    408 

ValueError: x must be one of None, 'Depth', 'XC', 'YC', 'rA'
```
Computing the divergence:
```Python
ospy.compute.divergence(od, 'UVEL', 'VVEL')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-89-9b116fdf9c25> in <module>()
----> 1 ospy.compute.divergence(od, 'UVEL', 'VVEL')

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/oceanspy/compute.py in divergence(od, iName, jName, kName, aliased)
    405         # Add missing variables
    406         varList = ['HFacC', 'rA', 'dyG', 'HFacW', NameIN]
--> 407         od = _add_missing_variables(od, varList)
    408 
    409         # Check components

/home/daanr/miniconda3/envs/oceanography/lib/python3.6/site-packages/oceanspy/compute.py in _add_missing_variables(od, varList, FUNC2VARS)
    129                          ' please open an issue on GitHub:'
    130                          '\n https://github.com/malmans2/oceanspy/issues'
--> 131                          ''.format(var_error))
    132 
    133     # Compute new variables

ValueError: These variables are not available and can not be computed: ['HFacC', 'HFacW'].
If you think that OceanSpy should be able to compute them, please open an issue on GitHub:
 https://github.com/malmans2/oceanspy/issues
```

**Comment by asiddi24** [comment]
Thanks for opening the issue @daanreijnders . An obvious fix is to make sure that your dataset variable names are the same as that used by OceanSpy. So, when you first create the `OceanDataset`, make a quick check whether the variable names imported are compatible with OceanSpy or not. Most times they should be if you're using an MITgcm output, but sometimes it doesn't such as with ECCO data, where you need to set aliases to certain variables like `hFacC`, `hFacW` etc.

[Here's](https://oceanspy.readthedocs.io/en/latest/Tutorial.html#Import-datasets) where you can see the list of variables as used in OceanSpy and subsequently use ['OceanDataset.set_aliases'](https://oceanspy.readthedocs.io/en/latest/generated/oceanspy.OceanDataset.set_aliases.html#oceanspy.OceanDataset.set_aliases) to make changes to these names. 

Both errors above seem to be arising from this. Let us know if this doesn't work.

As for setting the grid, I think @malmans2 might be able to shed some light to it.

**Comment by daanreijnders** [comment]
I didn't notice the difference in capitalisation between `hFacC` and `HFacC`. Thanks for pointing that out. After setting aliases, I get the same error with the first example (plotting the horizontal section). For the second example, it seems there's still incompatibility with `xmitgcm`, which stores `UVEL` with coordinates `YC` and `XG` (`XG` is the x-coordinate of the f-points). OceanSpy expects `Xp1` instead.

**Comment by asiddi24** [comment]
So, there are certain checks that are in place while importing from any format, making sure it's compatible with OceanSpy.
**I will try and demonstrate that with a test dataset used by xmitgcm** [here](https://xmitgcm.readthedocs.io/en/latest/quick_start.html). Since, your dataset seems to be similar to in format, I hope it works for you too.

Once the dataset is read, i.e
```python
data_dir = "./global_oce_latlon"
ds = xmitgcm.open_mdsdataset(data_dir, calendar="360_days",
                             read_grid=True, geometry="cartesian")
```
We rename the center and corner points from `XC`, `XG` to `X` and `Xp1` and create the `OceanDataset`
```python
# Rename X and Y
rename_dict = {'XC': 'X', 'YC': 'Y', 'XG': 'Xp1', 'YG': 'Yp1'}
ds = ds.rename(rename_dict)
od = ospy.OceanDataset(ds)
```

**Now, the important part**, where OceanSpy creates required coordinates from `X`, `Y`, `Xp1` and `Yp1` using `oceanspy.OceanDataset.manipulate_coords`. You might want to check [out](https://oceanspy.readthedocs.io/en/latest/generated/oceanspy.OceanDataset.manipulate_coords.html#oceanspy.OceanDataset.manipulate_coords) this function. `XC` and `XG` are now implemented here as 2D coordinates.

```python
od = od.manipulate_coords(fillna = False, coords1Dfrom2D=False, coords2Dfrom1D=True, coordsUVfromG=False)
```
The coordinates now look like this,

<img src="https://user-images.githubusercontent.com/43628137/91114265-810ddf00-e655-11ea-9d20-052965c7c7fb.png" width="600">

The grid is also set accordingly, 
```python
od = od.set_grid_coords(
       {
        "time": {"time": 0},
        'Y': {'Y': None, 'Yp1': 0.5},
        'X': {'X': None, 'Xp1': 0.5},
        'Z': {'Z': None, 'Zp1': 0.5, 'Zu': 0.5, 'Zl': -0.5},
        },
        overwrite=True )
```
OceanSpy now plots without any issues
```python
ax = od.plot.horizontal_section(varName = 'Depth')
```
<img src="https://user-images.githubusercontent.com/43628137/91113607-042e3580-e654-11ea-9a27-0c2f56cbf194.png" width="400">

The issue with the divergence function is also solved with this correction of the coordinates. Making sure the aliases are in place.
```python
od = od.set_aliases(
                    {
                        'HFacC':'hFacC',
                        'HFacW':'hFacW',
                        'HFacS':'hFacS'
                    })
divergence = ospy.compute.divergence(od, 'UVEL','VVEL')
od = od.merge_into_oceandataset(divergence)

```

You can plot it and check it out 

```python
od.plot.horizontal_section(varName='dUVEL_dX', meanAxes='Z')
```

<img src="https://user-images.githubusercontent.com/43628137/91113616-06908f80-e654-11ea-9bcb-45387c22c5a4.png" width="400">

Hope that helps.

**Comment by daanreijnders** [comment]
Thanks so much for the clear explanation! I was confused because `Xp1` in MITgcm normally has length `nx+1`, while my data in the x-direction is of length `nx`, but I see now that I just could've renamed `XG`. So my problem was a little trivial in hindsight. Thanks for bearing with me.
