### ISSUE TITLE
Add function to analyze particles

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#16]
* OceanSpy version: 0.0.9

### Description
Investigate the model using the positions returned by the particle code.

**Comment by malmans2** [comment]
@renskegelderloos 

Here are a few thoughts about the new function:
* Add an input variable to specify the limits of the vertical cutout (currently add 30m and is hard-coded). Something similar to ``add_bdr`` for ``subsample.servey``. I think in the future we should actually add a vertical and horizontal resolution to ``info``, so these functions automatically add a few meters/km when interpolation is needed.
* If you need monotonically increasing values to interpolate, I would sort them ([using these functions](http://xarray.pydata.org/en/stable/reshaping.html#sort)) instead of computing the absolute value. ``deps = _xr.ufuncs.fabs(deps)`` works with the current dataset, but it would fail with datasets that have flipped Z (e.g., Z= [-10, -5, 0])
* Output a different ``info`` class: ``info.grid`` should be a string that describe the dataset (similar to ``subsample.survey``).
* Is this the most efficient interpolation? Can we use something more efficient for ``xarray``? Maybe this issue is useful: https://github.com/JiaweiZhuang/xESMF/issues/24

**Comment by renskegelderloos** [comment]
@malmans2 

I have rewritten and improved the function. (i) Your first item is no longer relevant because of the changes made in subsample.cutout. (ii) Xarray's interpolation does not require flipping axes, so this part has been taken out. (iii) info.grid is now set to 'Particle locations'. (iv) Great idea; done.

**Comment by malmans2** [comment]
Great! I'm going to close this issue!
Does it fix #42 ? If yes, feel free to close it.
