### ISSUE TITLE
Error in subsampling

### ISSUE THREAD

**Issue by jdldeauna** [hainegroup/oceanspy#170]
* OceanSpy version: 0.2.0

### Description

I'm trying to use OceanSpy to subsample from a dataset. I was able to create the OceanSpy dataset, but using subsample.cutout results in an error. I haven't been able to find a similar case online and would appreciate any help, thanks!

### What I Did

```
Commands:

od = ospy.OceanDataset(ds)
od.dataset.coords

Output:

Coordinates:
    nav_lat  (y, x) float32 dask.array<chunksize=(332, 362), meta=np.ndarray>
    nav_lon  (y, x) float32 dask.array<chunksize=(332, 362), meta=np.ndarray>
  * olevel   (olevel) float32 0.50576 1.5558553 ... 5698.0605 5902.0576
  * time     (time) datetime64[ns] 1850-01-16T12:00:00 ... 2014-12-16T12:00:00

Commands:

od_cut = od.subsample.cutout(
    XRange=[-150, -100], YRange=[20, 60]
)

Output:

KeyError                                  Traceback (most recent call last)
~/.../lib/python3.9/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
   1171         try:
-> 1172             variable = self._variables[name]
   1173         except KeyError:

KeyError: 'YG'


```

**Comment by malmans2** [comment]
Hi @jdldeauna ,

You are getting this error because OceanSpy needs all variables describing the staggered grids and uses MITgcm naming conventions. In your example the subsampling function can't find `YG`, which is the latitude of the corner points.

The best way to set up all variables used by OceanSpy is through intake catalogs (see for example [here](https://github.com/hainegroup/oceanspy/blob/master/sciserver_catalogs/catalog_xarray.yaml)) and then use [oceanspy.open_oceandataset.from_catalog](https://oceanspy.readthedocs.io/en/latest/generated/oceanspy.open_oceandataset.from_catalog.html#oceanspy.open_oceandataset.from_catalog).

Looks like you are not using MITgcm output. If you have a small sample of your dataset that you can share (e.g., file describing all staggered grids + just one time step of output variables), I'd be happy to take a look and help you to get started!

**Comment by jdldeauna** [comment]
Hi @malmans2 ,

Thank you for your response! I wonder if OceanSpy can be used for model output aside from MITgcm? I'm trying to use it for an Earth System Model. Below is code I use for extracting sample data. Then I used ds with OceanSpy commands as I stated in my earlier post. 

`````

import matplotlib.pyplot as plt
import xarray as xr
import numpy as np
import cmocean.cm as cmo

url = "https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json"
col = intake.open_esm_datastore(url)
cat = col.search(
    table_id='Omon',
    grid_label='gn',
    experiment_id='historical',
    member_id='r1i1p1f1',
    variable_id=['so', 'thetao'],
    source_id=['CESM2']
)

from cmip6_preprocessing.preprocessing import combined_preprocessing
ddict = cat.to_dataset_dict(
    zarr_kwargs={'consolidated':True, 'decode_times':True},
    preprocess=combined_preprocessing
)
ds = ddict['CMIP.NCAR.CESM2.historical.Omon.gn']
ds

**Comment by jdldeauna** [comment]
Hi @malmans2 ,

I had a question about using the intake catalog. Since they have separate .yaml files, should I uninstall then reinstall the OceanSpy package using these environment files?

Please see also attached a sample netcdf file of data. Thanks!

[sample_file_IPSL.nc.zip](https://github.com/hainegroup/oceanspy/files/5991984/sample_file_IPSL.nc.zip)

**Comment by malmans2** [comment]
Hi @jdldeauna,

The issue with your dataset is that it doesn't have all the information describing the staggered grids, which is needed by OceanSpy. Looks like the ocean component of the model you are using is NEMO: All grid variables are usually stored in a file named domain_cfg.nc.

**Comment by jdldeauna** [comment]
Hello @malmans2 ,

Thank you for your help! As an alternative to getting the grid variable files per ocean model, would it be enough to rename the variables in datasets to be used according to the [conventions for MITgcm](https://xmitgcm.readthedocs.io/en/latest/usage.html#dimensions-and-coordinates)?

**Comment by asiddi24** [comment]
You can do that using the [set](https://oceanspy.readthedocs.io/en/latest/api.html#set) functions in OceanSpy. Although, I think what you're looking for would be to generate the grid variables or coordinates using `OceanDataset.manipulate_coords`. You can find the API for that [here](https://oceanspy.readthedocs.io/en/latest/generated/oceanspy.OceanDataset.manipulate_coords.html#oceanspy.OceanDataset.manipulate_coords)

**Comment by jdldeauna** [comment]
Great, thank you so much!
