### ISSUE TITLE
Migrate CI

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#171]
We should migrate CI from Travis to GitHub actions as the free plan of Travis changed.

**Comment by ThomasHaine** [comment]
Sounds fine to me. What's changed and what are the implications for CI with GH actions?

**Comment by malmans2** [comment]
The limits of free builds/minutes/concurrent jobs have been reduced. There are no limits for public repos using GH. The CI will work exactly as before (install conda env with python 3.6, 3.7, 3.8 and run pytest), we just have to change the configuration files. `.github/workflows/CI.yaml` will replace `.travis.yaml`

**Comment by ThomasHaine** [comment]
Sounds good!
