### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#216]
We should rename master to main. Hopefully it's going to be easy.
For example, I think GitHub workflows are a bit confused.
The weekly CI is running OK, but the main page is still showing the CI triggered by the last commit:
<img width="753" alt="Screenshot 2022-02-11 at 10 44 41" src="https://user-images.githubusercontent.com/22245117/153578185-86e56f7a-9e33-40bf-bc5b-427bfd36cd21.png">
CI is currently failing, but that is showing a pass.

Anyways, renaming would be good even if everything is OK.
See: https://github.com/github/renaming

**Comment by Mikejmnez** [comment]
I agree we should rename to `main`. I guess is that this has to be done by the owner of the organization, so Tom right?

**Comment by ThomasHaine** [comment]
@malmans2 you have admin privileges so you should do it I think. Let me know if you need help.

**Comment by malmans2** [comment]
Yes, I think I can do it. Let's wait until we merge all open PRs.

**Comment by Mikejmnez** [comment]
We have closed and merged PRs. @malmans2 feel free to rename `master` to `main`.

**Comment by ThomasHaine** [comment]
Let's merge #235 and #237 and then I'll rename `master` -> `main`

**Comment by malmans2** [comment]
I think everyone with admin permissions can do this! Let me know if you're not able to do it though.

**Comment by ThomasHaine** [comment]
Done.
