### ISSUE TITLE
TEOS10

### ISSUE THREAD

**Issue by renskegelderloos** [hainegroup/oceanspy#33]
* OceanSpy version: 0.0.10

### Description

Add TEOS option (not default) into Oceanspy

**Comment by malmans2** [comment]
It looks like TEOS is not compatible with xarray (no lazy computation). I think it makes sense to have it in the oceanography image, without using it in OceanSpy. I added another equation of state though (mdjwf).

**Comment by ThomasHaine** [comment]
I would find TEOS-10 useful too (e.g., more flexible density calculation, freezing point, thermodynamics).

**Comment by malmans2** [comment]
I will add it in the oceanography image. Although I don't think it supports lazy arrays, it's definitely helpful. I think you can just pass DataArrays to gsw functions, but if it doesn't work, then use numpy arrays (e.g. `Temp = od.dataset['Temp'].values`).

Here is the python package: https://teos-10.github.io/GSW-Python/
Installation from terminal: `conda install gsw`

**Comment by ThomasHaine** [comment]
Hmmm. conda install gsw doesn’t work for me.



On Feb 22, 2019, at 10:00 AM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


I will add it in the oceanography image. Although I don't think it supports lazy arrays, it's definitely helpful. I think you can just pass DataArrays to gsw functions, but if it doesn't work, then use numpy arrays (e.g. Temp = od.dataset['Temp'].values).

Here is the python package: https://teos-10.github.io/GSW-Python/
Installation from terminal: conda install gsw

**Comment by malmans2** [comment]
`pip install gsw` should work.
