### ISSUE TITLE
Missing attributes (units, description, ...)

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#53]
* OceanSpy version: Latest 20Feb19

There appears to be no units Attribute for variable "S". Even if it's no unit ("none"?) we should include it for consistency. This is for EGshelfIIseas2km_ASR

**Comment by malmans2** [comment]
Good point. I didn't add any info to the original NetCDFs. There are are few variables without description or units (e.g., velocities don't have description). Let's use this issue to report missing info.

Also, there are a few packages that support units (units are not just a string). Xarray doesn't support units yet, but there are some discussions on the implementation: https://github.com/pydata/xarray/issues/525

**Comment by malmans2** [comment]
Also, some of the variables computed by OceanSpy might need better description and/or units.

**Comment by malmans2** [comment]
This is actually still open in #63 . The new open function is more generic and I didn't want to hard-code the extra attributes.
