### ISSUE TITLE
linter report

### ISSUE THREAD

**Issue by rabernat** [hainegroup/oceanspy#64]
I ran [flake8](http://flake8.pycqa.org/en/latest/) on your codebase to verify its compliance with the Python [PEP8 style guide](https://www.python.org/dev/peps/pep-0008/). Following PEP8 is important it makes the code much more readable for experienced python developers and indicates you are trying to follow best practices. This makes it more likely that other will want to contribute via pull requests.

The standard python line length is 79 characters, but many people find that too restrictive.  

The results of `flake8 --max-line-length=120 --ignore E402,E731,E741,W503,W504` (same ignore settings as xarray) are [here](https://gist.github.com/rabernat/453e6556c2afe5f9b0339bf56cfb155b). There were 5365  errors and warning identified.

**Comment by malmans2** [comment]
Thanks! I'm sure we would have to put the code in decent shape first, but what are your thoughts on [black](https://github.com/ambv/black)?

**Comment by rabernat** [comment]
Black seems like a great tool and could certainly fix up these issues mostly automatically.

In xarray we use [pep8speaks](https://github.com/OrkoHunter/pep8speaks) to enforce PEP8 and are mostly happy with it. We tried [stickler](https://stickler-ci.com/) in xmitgcm but we basically hated it.
