### ISSUE TITLE
Okubo-Weiss parameter bug

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#68]
import oceanspy          as ospy
od = ospy.open_oceandataset.get_started()
od.compute.Okubo_Weiss_parameter()

gives an error:

/home/idies/miniconda3/lib/python3.7/site-packages/dask/array/blockwise.py:204: UserWarning: The da.atop function has moved to da.blockwise
  warnings.warn("The da.atop function has moved to da.blockwise")
AttributeErrorTraceback (most recent call last)
<ipython-input-1-fb60e628e83a> in <module>
      1 import oceanspy          as ospy
      2 od = ospy.open_oceandataset.get_started()
----> 3 od.compute.Okubo_Weiss_parameter()

AttributeError: '_computeMethdos' object has no attribute 'Okubo_Weiss_parameter'

**Comment by malmans2** [comment]
@ThomasHaine I think it's already fixed in the pull request I'm working on right now (#63 ). Planning to merge tomorrow when I'm done implementing Intake. In the meantime, you can do this:
```bash
$ git clone https://github.com/malmans2/oceanspy.git  --branch complete_tests --single-branch
```
Then install with the `-e` flag.

**Comment by ThomasHaine** [comment]
Yes, that works. Thanks!
