### ISSUE TITLE
pytest fails on laptop

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#69]
I tried oceanspy on my laptop and hit many failures with pytest (see pytest.txt).

Setup environment:
conda config --remove channels defaults
conda config --add channels conda-forge
conda install -y dask distributed bottleneck netCDF4 xarray cartopy esmpy ffmpeg
pip install geopy xgcm xesmf xmitgcm
pip install gsw
git clone https://github.com/malmans2/oceanspy.git
pip install -e oceanspy/
cd oceanspy
pytest oceanspy

[pytest.txt](https://github.com/malmans2/oceanspy/files/3009508/pytest.txt)

**Comment by malmans2** [comment]
I think most of the problems are due to this: #66
Can you please try this:
```bash
pip install xgcm==0.1.0
```
(check the terminal and make sure that xgcm v0.2 is uninstalled).
Then run the tests again.

**Comment by ThomasHaine** [comment]
Yes, that mainly fixes it. Now there are just a few skips and warnings:

[pytest.txt](https://github.com/malmans2/oceanspy/files/3010051/pytest.txt)

Thanks!
