### ISSUE TITLE
Opening EGshelfIIseas2km_ASR bug

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#72]
od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR')

gives:

ValueErrorTraceback (most recent call last)
<ipython-input-2-7122091215ab> in <module>
      1 # Open the oceandataset
----> 2 od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR')
      3 #od = ospy.open_oceandataset.from_catalog('get_started')
      4 
      5 # Report some basic information on the oceandataset

~/workspace/Storage/Thomas.Haine/persistent/OceanSpy_dev/oceanspy/oceanspy/open_oceandataset.py in from_catalog(name, catalog_url)
    199 
    200     # Merge
--> 201     ds = _xr.merge(datasets)
    202 
    203     # Consistent chunking

~/miniconda3/lib/python3.7/site-packages/xarray/core/merge.py in merge(objects, compat, join)
    530         for obj in objects]
    531 
--> 532     variables, coord_names, dims = merge_core(dict_like_objects, compat, join)
    533     # TODO: don't always recompute indexes
    534     merged = Dataset._construct_direct(

~/miniconda3/lib/python3.7/site-packages/xarray/core/merge.py in merge_core(objs, compat, join, priority_arg, explicit_coords, indexes)
    443 
    444     coerced = coerce_pandas_values(objs)
--> 445     aligned = deep_align(coerced, join=join, copy=False, indexes=indexes)
    446     expanded = expand_variable_dicts(aligned)
    447 

~/miniconda3/lib/python3.7/site-packages/xarray/core/alignment.py in deep_align(objects, join, copy, indexes, exclude, raise_on_invalid)
    215 
    216     aligned = align(*targets, join=join, copy=copy, indexes=indexes,
--> 217                     exclude=exclude)
    218 
    219     for position, key, aligned_obj in zip(positions, keys, aligned):

~/miniconda3/lib/python3.7/site-packages/xarray/core/alignment.py in align(*objects, **kwargs)
    144                     'aligned because they have different dimension size(s) %r '
    145                     'than the size of the aligned dimension labels: %r'
--> 146                     % (dim, unlabeled_sizes, labeled_size))
    147 
    148     for dim in unlabeled_dim_sizes:

ValueError: arguments without labels along dimension 'Z' cannot be aligned because they have different dimension size(s) {55} than the size of the aligned dimension labels: 216

**Comment by ThomasHaine** [comment]
OK, I see the name of the dataset changed. od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR_full') works.

I was confused because od = ospy.open_oceandataset.from_catalog('EGshelfIIseas2km_ASR') gives "Opening EGshelfIIseas2km_ASR." immediately then waits ~50secs before throwing the error message. Parse the input string first and filter the errors straightaway?

**Comment by malmans2** [comment]
Yes I agree. Waiting 1min because of a typo is annoying and confusing. I've added a check on the datasets stored on SciServer.
