### ISSUE TITLE
v.0.12 release and JOSS submission

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#90]
Final tasks:
- [x] Update SciServer Oceanography image: @malmans2 
- [x] Lagrangian use case: @malmans2 @hooteoos-waltz 
- [x] Volumetric census use case: @ThomasHaine 
- [x] Feedback on new documentation (e.g., quick start): @renskegelderloos @asiddi24 

Edit: @asiddi24 is leading a use case on budgets. It probably won't be ready before submission. Let's keep the discussion in #71.

**Comment by ThomasHaine** [comment]
Will do. I'll build a tutorial example and you and I can discuss how to do the 2D T/S volumetric census.

Question: Is there an xarray mode method?  I can't find it. I want to avoid using scipy [https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html] if possible

**Comment by asiddi24** [comment]
Just in case their is a problem with building the paper from the paper.md file, here is the fix to one of the issues with it that I encountered.

https://github.com/retorquere/zotero-better-bibtex/issues/659#issuecomment-298317866

**Comment by ThomasHaine** [comment]
Mattia, I've made some progress on the volumetric census use case. See: Statistics tutorial0.ipynb in my folder in your OceanSpy_Tutorials folder on SciServer. Some issues:

- Dask no longer works although it works without dask. I don't know why.
- Is there an xarray statistical function to compute the mode?
-  We need to talk about how to achieve the volumetric census by binning over T/S simultaneously. Once this is done I think the use case will be complete.

Please let me have your comments!

**Comment by malmans2** [comment]
@ThomasHaine , @renskegelderloos  I've uploaded the particle tutorial by me and @hooteoos-waltz. Here is the link: https://oceanspy.readthedocs.io/en/latest/Particles.html 
The goals are to show particle extraction, SciServer Jobs vs Interact, and some more advanced use of OceanSpy functions (e.g., more complex plots, masking, ...).
If you want to run the notebook on SciServer, you can use the following command to download it:
```wget https://raw.githubusercontent.com/malmans2/oceanspy/master/docs/Particles.ipynb```.

I'm on the tutorial by @ThomasHaine now.

**Comment by malmans2** [comment]
@ThomasHaine: I made a couple of edits and added the notebook in your folder (`OceanSpy_Tutorials/Tom/Statistics_tutorial1.ipynb`). The notebook is now following [PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/).

> Dask no longer works although it works without dask. I don't know why.

Fixed! `.load()` needs to be called if dask is already operating on the `DataArray`.

> Is there an xarray statistical function to compute the mode?

I don't think so, so I would just use you the function `bin_snapshot` that you created. I get the same results for mode and weighted mode. Although is surprising, I don't think it is necessarily wrong. Let me know if you find a bug.

> We need to talk about how to achieve the volumetric census by binning over T/S simultaneously.

I think the only way to achieve this is a very sophisticated notebook. I suggest we don't include it for now, and we implement a `volumetric census` function in OceanSpy in the future.

Can you please add it in the documentation and submit a PR when you are done? The notebook need to be added in this folder: https://github.com/malmans2/oceanspy/tree/master/docs. You also need to add the notebook name here: https://github.com/malmans2/oceanspy/blob/master/docs/index.rst.
